services:
  metabase:
    image: metabase/metabase:latest
    container_name: funnelmart-metabase
    ports:
      - "3001:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_HOST: funnelmart-postgres
      MB_DB_PORT: 5432
      MB_DB_DBNAME: funnelmart
      MB_DB_USER: funnelmart
      MB_DB_PASS: funnelmart
    networks:
      - funnelmart_net

networks:
  funnelmart_net:
    external: true
    name: funnelmart_default
